/**
 * mutation-types.js
 */

export const SET_API_FETCHING = 'SET_API_FETCHING'
export const UPDATE_QUERY = 'UPDATE_QUERY'
export const UPDATE_GIF_ID = 'UPDATE_GIF_ID'
export const STORE_SINGLE_RESPONSE = 'STORE_SINGLE_RESPONSE'
export const STORE_SEARCH_RESPONSE = 'STORE_SEARCH_RESPONSE'
export const STORE_FAVORITES_RESPONSE = 'STORE_FAVORITES_RESPONSE'
export const ADD_FAVORITE = 'ADD_FAVORITE'
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE'
export const CLEAR_GIPHY_SEARCH_TERMS = 'CLEAR_GIPHY_SEARCH_TERMS'
export const CLEAR_GIPHY_API_CACHE = 'CLEAR_GIPHY_API_CACHE'

